apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: i507fo6aj-go-gitops
  description: This is GitOps manifest for i507fo6aj-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: i507fo6aj-go
    janus-idp.io/tekton: i507fo6aj-go
    backstage.io/kubernetes-id: i507fo6aj-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:i507fo6aj-go
