apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i507fo6aj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i507fo6aj-go 
  name: i507fo6aj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: i507fo6aj-go 
